Merge custom TOC code into upstream
jackorcherton/HackIt pull request #12
Opened 2023-01-12 23:14 UTC by sharkmoos

As you suggested in Cov-ComSecCov-ComSec.github.io#58. I have removed the code changing the functionality of the TOC font matter, so this is just the shortcode code for adding a toc. 

As mentioned in  Cov-ComSecCov-ComSec.github.io#58, the text is still blue. I will make it grey when I feel like spending more time trying random things hoping SCSS starts making sense

2023-01-14 19:35 UTC, jackorcherton commented
Thanks Sharkmoo's I'll take a look and will investigate the current behaviour

2023-01-15 21:19 UTC, jackorcherton commented
@sharkmoos, what do you mean by shortcode?

As mentioned in https://github.com/Cov-ComSec/Cov-ComSec.github.io/pull/58, I think this theme already has the functionality you need (or please correct me if I'm wrong?)

2023-01-15 23:01 UTC, sharkmoos commented
Sure, let me run you through the change I'm proposing here.

From the [Cov-ComSec/Cov-ComSec.github.io/pull/58](https://github.com/Cov-ComSec/Cov-ComSec.github.io/pull/58), I stated the following, TOC can now be disabled via a page's font matter with the following line toc: false

> TOC can now be disabled via a page's font matter with the following line `toc: false`

This change not been suggested for this theme, as we are still testing the impact o

2023-01-15 23:04 UTC, sharkmoos commented
Sure, let me run you through the change I'm proposing here.

From the https://github.com/Cov-ComSec/Cov-ComSec.github.io/pull/58, I stated the following, TOC can now be disabled via a page's font matter with the following line `toc: false`

> TOC can now be disabled via a page's font matter with the following line toc: false

This change not been suggested for your upstream, as we are still testing the impact of the change


The change proposal here is around shortcodes. For your question about "what do you mean by shortcodes", I am talking about the Hugo template rendering wrappers. The purpose of the TOC shortcode proposed is to provide the functionality to place a TOC anywhere on a post, rather than it being generated at the top of the page. The TOC can be inserted into a page by providing the following shortcode in the source code of the page 

```go
{{< toc >}}
```

2023-01-16 08:01 UTC, jackorcherton commented
Ah ok, thanks for the explanation, this seems useful

I'll take a proper look when I get the chance before merging.

2023-01-17 20:20 UTC, jackorcherton commented
Can confirm that the positioning works successfully with my site, however it seems to break the active colours when you hover over a link.

2023-01-17 21:58 UTC, sharkmoos commented
Oh interesting. I think I have active colour contrasts disabled on my browser. I'll take a look at that, there may be a reasonable fix

2023-01-17 21:58 UTC, sharkmoos commented
Can you send the colour code of the active colour>

2023-01-17 22:17 UTC, sharkmoos commented
I pulled to colour code from 7e27d8e726556cbe23f7216b0e98cc9f768cebbb. This looks correct to you now?

2023-01-20 21:27 UTC, jackorcherton requested changes
@sharkmoos Believe these 2 changes fix the menu colours.


I'll let you check you're happy with this, and if you are, we'll merge :)

2023-01-20 21:27 UTC, jackorcherton commented on assets/css/_partial/_shortcodes/toc.scss
> +        color: $single-link-hover-color;
```suggestion
        color: $single-link-color;

```

2023-01-20 21:27 UTC, jackorcherton commented on assets/css/_partial/_shortcodes/toc.scss
> +          color: $single-link-hover-color-dark;
```suggestion
          color: $single-link-color-dark;

```

2023-01-20 21:40 UTC, sharkmoos commented
What is the change here? The colour of the vertical bar to the left of the text? I'm not sure I see the difference?

ComSec website vs yours, is it slightly darker or something?

![image](https://user-images.githubusercontent.com/23018541/213810094-2f970b1c-ed88-440f-8f1a-4a3371ee44b2.png)

2023-01-20 21:43 UTC, jackorcherton commented
Yep should be slightly darker to match the original theme.

Also, are you running it locally, as I haven't pushed this to my live site

2023-01-20 21:45 UTC, sharkmoos commented
Sweet. No, not running locally. But your site has the [jackorcherton](https://github.com/jackorcherton) /
[HackIt](https://github.com/jackorcherton/HackIt) theme, and the comsec one is running the newest [[Cov-ComSec](https://github.com/Cov-ComSec) /
[HackIt](https://github.com/jackorcherton/HackIt)](https://github.com/Cov-ComSec/Cov-ComSec.github.io)

2023-01-20 21:46 UTC, sharkmoos commented
These looks great then, I'll approve those

2023-01-20 21:47 UTC, jackorcherton commented
The ComSec site is running with the changes I just made?

2023-01-20 21:48 UTC, jackorcherton commented
Thought it should match now...

2023-01-20 21:49 UTC, sharkmoos commented
No - your website has the *original* hackit theme, which is what we're trying to emulate? The ComSec website should have the theme with the incorrect vertical bar

2023-01-20 21:50 UTC, jackorcherton commented
Yes but hopefully after this push they should be the same 🤞

2023-01-20 21:55 UTC, sharkmoos commented
Sweet. Your update is done, feel free to merge

2023-01-20 22:00 UTC, jackorcherton commented
Awesome

2023-01-20 22:04 UTC, merged